[project]
name = "osprei"
version = "0.1.0"
description = "an AI-powered diagnostics assistant for Kubernetes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kubernetes>=32.0.1",
    "langchain-anthropic>=0.3.9",
    "langgraph>=0.3.5",
]
